In [13]:
import numpy as np
import pandas as pd

from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

from matplotlib import pyplot

In [31]:
data = pd.read_csv("cancer patient data sets.csv")
data.pop('Patient Id')
data.pop('index')
data.pop('chronic Lung Disease')
data.pop('Balanced Diet')
data.pop('Air Pollution')
data.pop('Swallowing Difficulty')
data.pop('Fatigue')
data.pop('Clubbing of Finger Nails')
data.pop('Snoring')
data.pop('Coughing of Blood')
data.pop('OccuPational Hazards')
data.pop('Genetic Risk')
data.pop('Passive Smoker')
data.pop('Obesity')
data.pop('Frequent Cold')
data.pop('Weight Loss')

data

,Age,Gender,Alcohol use,Dust Allergy,Smoking,Chest Pain,Shortness of Breath,Wheezing,Dry Cough,Level
0,33,1,4,5,3,2,2,2,3,Low
1,17,1,1,5,2,2,7,8,7,Medium
2,35,1,5,6,2,4,9,2,7,High
3,37,1,7,7,7,7,3,1,7,High
4,46,1,8,7,8,7,4,1,2,High
...,...,...,...,...,...,...,...,...,...,...
995,44,1,7,7,7,7,2,7,5,High
996,37,2,8,7,7,7,5,7,1,High
997,25,2,5,6,2,4,9,2,7,High
998,18,2,8,7,8,7,4,1,2,High
999,47,1,5,6,2,4,9,2,7,High

In [40]:
X = np.array(data.drop('Level', axis=1))
y = np.array(data['Level'])